services:
  - type: web
    name: scuolamerenda
    env: node
    buildCommand: ./deploy.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
    healthCheckPath: /api/health